# 系統配置
system:
  host: "0.0.0.0"
  port: 5001
  env: debug
# 日誌配置
logger:
  level: info
  prefix: "[gin-admin-api]"
  director: logger
  show_line: true
  log_in_console: true
# mysql配置
mysql:
  host: 127.0.0.1
  port: 3306
  db: gin-blog
  username: root
  password: qweasd
  log_level: dev
  charset: utf8
  maxIdle: 50
  maxOpen: 150
# redis配置
redis:
  address: 127.0.0.1:6379
  password: 123456
  # 0~15個
  db: 0
